source 'http://rubygems.org'

gem 'rails', '3.2.9'
gem 'jquery-rails', '2.1.1'

gem 'eventmachine'

group :test, :development do
  gem 'sqlite3'
end

group :production do
  gem 'mysql'
end

group :test, :development do
  gem 'factory_girl', '~> 4.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rspec-rails', '~> 2.0'
end

group :test do
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
end

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

gem 'passenger'
gem 'thin'

# rails g rspec:install


